### ISSUE TITLE
hacktoberfest PR status issue

### ISSUE THREAD

**Issue by pravocodes** [Rajspeaks/Code-Pyramid#15]
they are saying that your repository in not participating in Hacktoberfest, please solve this issue.

**Comment by Rajspeaks** [comment]
Send the screenshot

**Comment by pravocodes** [comment]
![WhatsApp Image 2022-10-02 at 00 49 16](https://user-images.githubusercontent.com/114364779/193424995-9c4a5600-782d-4dd8-bdb0-04219eda4a79.jpeg)
![image](https://user-images.githubusercontent.com/114364779/193425008-841821d6-41e8-4ba8-8119-52e167f3aeae.png)

**Comment by Rajspeaks** [comment]
Create a New PR with any other C++ code

**Comment by pravocodes** [comment]
ok

**Comment by pravocodes** [comment]
![image](https://user-images.githubusercontent.com/114364779/193425483-62dda67a-59e5-4ab1-9d29-9de3ca31c5a5.png)
Now it is showing this.

**Comment by Rajspeaks** [comment]
Yes, because that time I still had not reviewed or labelled it as hacktoberfest-accepted. That's why.

Just I labelled it. It showing waiting status.
